name: .NET

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false 

     # Add NuGet Sources

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    - name: Add GGroupp NuGet Source
      run: dotnet nuget add source ${{ secrets.GGROUPP_NUGET_SOURCE_URL }} -n ggroupp -u ${{ secrets.GGROUPP_NUGET_SOURCE_USER_NAME }} -p ${{ secrets.GGROUPP_NUGET_SOURCE_USER_PASSWORD }} --store-password-in-clear-text

    # Api.Core.FailureCode

    - name: Restore Api.Core.FailureCode
      run: dotnet restore ./src/*/*/Api.Core.FailureCode.csproj

    - name: Build Api.Core.FailureCode
      run: dotnet build ./src/*/*/Api.Core.FailureCode.csproj --no-restore  -c Release

    - name: Pack Api.Core.FailureCode
      run: dotnet pack ./src/*/*/Api.Core.FailureCode.csproj --no-restore -o ~/nuget  -c Release

    # Api.Core.EntityKey

    - name: Restore Api.Core.EntityKey
      run: dotnet restore ./src/*/*/Api.Core.EntityKey.csproj

    - name: Build Api.Core.EntityKey
      run: dotnet build ./src/*/*/Api.Core.EntityKey.csproj --no-restore  -c Release

    - name: Pack Api.Core.EntityKey
      run: dotnet pack ./src/*/*/Api.Core.EntityKey.csproj --no-restore -o ~/nuget  -c Release

    # Api.Core.EntityKey.Tests

    - name: Restore Api.Core.EntityKey.Tests
      run: dotnet restore ./src/*/*/Api.Core.EntityKey.Tests.csproj

    - name: Test Api.Core.EntityKey.Tests
      run: dotnet test ./src/*/*/Api.Core.EntityKey.Tests.csproj --no-restore  -c Release

    # Api.Abstractions.Search

    - name: Restore Api.Abstractions.Search
      run: dotnet restore ./src/*/*/Api.Abstractions.Search.csproj

    - name: Build Api.Abstractions.Search
      run: dotnet build ./src/*/*/Api.Abstractions.Search.csproj --no-restore  -c Release

    - name: Pack Api.Core.Search
      run: dotnet pack ./src/*/*/Api.Abstractions.Search.csproj --no-restore -o ~/nuget  -c Release

    # Api.Abstractions.EntityUpdate

    - name: Restore Api.Abstractions.EntityUpdate
      run: dotnet restore ./src/*/*/Api.Abstractions.EntityUpdate.csproj

    - name: Build Api.Abstractions.EntityUpdate
      run: dotnet build ./src/*/*/Api.Abstractions.EntityUpdate.csproj --no-restore  -c Release

    - name: Pack Api.Abstractions.EntityUpdate
      run: dotnet pack ./src/*/*/Api.Abstractions.EntityUpdate.csproj --no-restore -o ~/nuget  -c Release

    # Api.Abstractions.EntityDelete

    - name: Restore Api.Abstractions.EntityDelete
      run: dotnet restore ./src/*/*/Api.Abstractions.EntityDelete.csproj

    - name: Build Api.Abstractions.EntityDelete
      run: dotnet build ./src/*/*/Api.Abstractions.EntityDelete.csproj --no-restore  -c Release

    - name: Pack Api.Abstractions.EntityDelete
      run: dotnet pack ./src/*/*/Api.Abstractions.EntityDelete.csproj --no-restore -o ~/nuget  -c Release

    # Api.Abstractions.EntityCreate

    - name: Restore Api.Abstractions.EntityCreate
      run: dotnet restore ./src/*/*/Api.Abstractions.EntityCreate.csproj

    - name: Build Api.Abstractions.EntityCreate
      run: dotnet build ./src/*/*/Api.Abstractions.EntityCreate.csproj --no-restore  -c Release

    - name: Pack Api.Abstractions.EntityCreate
      run: dotnet pack ./src/*/*/Api.Abstractions.EntityCreate.csproj --no-restore -o ~/nuget  -c Release

    # Api.Abstractions.EntitySetGet

    - name: Restore Api.Abstractions.EntitySetGet
      run: dotnet restore ./src/*/*/Api.Abstractions.EntitySetGet.csproj

    - name: Build Api.Abstractions.EntitySetGet
      run: dotnet build ./src/*/*/Api.Abstractions.EntitySetGet.csproj --no-restore  -c Release

    - name: Pack Api.Abstractions.EntitySetGet
      run: dotnet pack ./src/*/*/Api.Abstractions.EntitySetGet.csproj --no-restore -o ~/nuget  -c Release

    # Api.Abstractions.EntityGet

    - name: Restore Api.Abstractions.EntityGet
      run: dotnet restore ./src/*/*/Api.Abstractions.EntityGet.csproj

    - name: Build Api.Abstractions.EntityGet
      run: dotnet build ./src/*/*/Api.Abstractions.EntityGet.csproj --no-restore  -c Release

    - name: Pack Api.Abstractions.EntityGet
      run: dotnet pack ./src/*/*/Api.Abstractions.EntityGet.csproj --no-restore -o ~/nuget  -c Release

    # Api.Abstractions

    - name: Restore Api.Abstractions
      run: dotnet restore ./src/*/*/Api.Abstractions.csproj

    - name: Build Api.Abstractions
      run: dotnet build ./src/*/*/Api.Abstractions.csproj --no-restore  -c Release

    - name: Pack Api.Abstractions
      run: dotnet pack ./src/*/*/Api.Abstractions.csproj --no-restore -o ~/nuget  -c Release

    # Api

    - name: Restore Api
      run: dotnet restore ./src/*/*/Api.csproj

    - name: Build Api
      run: dotnet build ./src/*/*/Api.csproj --no-restore  -c Release

    - name: Pack Api
      run: dotnet pack ./src/*/*/Api.csproj --no-restore -o ~/nuget  -c Release

    # Api.Test

    - name: Restore Api.Test
      run: dotnet restore ./src/*/*/Api.Test.csproj

    - name: Test Api.Test
      run: dotnet test ./src/*/*/Api.Test.csproj --no-restore -o ~/nuget  -c Release

    # Api.Impersonation

    - name: Restore Api.Impersonation
      run: dotnet restore ./src/*/*/Api.Impersonation.csproj

    - name: Build Api.Impersonation
      run: dotnet build ./src/*/*/Api.Impersonation.csproj --no-restore  -c Release

    - name: Pack Api.Impersonation
      run: dotnet pack ./src/*/*/Api.Impersonation.csproj --no-restore -o ~/nuget  -c Release

    # Api.Impersonation.Test

    - name: Restore Api.Impersonation.Test
      run: dotnet restore ./src/*/*/Api.Impersonation.Test.csproj

    - name: Test Api.Impersonation.Test
      run: dotnet test ./src/*/*/Api.Impersonation.Test.csproj --no-restore -o ~/nuget  -c Release

    # Push

    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: dotnet nuget push "../../../nuget/*.nupkg" -s ${{ secrets.GGROUPP_NUGET_SOURCE_URL }} -k ${{ secrets.GGROUPP_NUGET_SOURCE_USER_PASSWORD }} --skip-duplicate
